- id: jsonschema-to-typeddict
  name: jsonschema-to-typeddict

  entry: python -m jsonschema_to_typeddict
  language: python
  minimum_pre_commit_version: 2.9.2
  require_serial: false
  types: [ json ]