[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "jsonschema_to_typeddict"
authors = [{name = "Henrique Gemignani Passos Lima", email = "henrique@gemignani.org"}]
readme = "README.md"
license = {file = "LICENSE"}
classifiers = ["License :: OSI Approved :: Apache Software License"]
dynamic = ["version", "description"]

[project.urls]
Home = "https://github.com/henriquegemignani/jsonschema-to-typeddict"